source 'https://rubygems.org'

# ruby '1.9.3'
gem 'locomotivecms_mounter', :git => 'git://github.com/dominatedominion/mounter.git', :ref => '81ccdb3a7d540b7159945ad913c3af1c3752104c'
gem 'locomotivecms_wagon', '~> 1.2.0'

group :development do
  # Mac OS X
  gem 'rb-fsevent', '~> 0.9.1', require: RUBY_PLATFORM.include?('darwin') && 'rb-fsevent'

  # Unix
  gem 'therubyracer', require: 'v8', platforms: :ruby
  gem 'rb-inotify', '~> 0.9', require: RUBY_PLATFORM.include?('linux') && 'rb-inotify'

  # Windows
  gem 'wdm', '>= 0.1.0', require: RUBY_PLATFORM =~ /mswin|mingw/i && 'wdm'
end

group :misc do
  # Add your extra gems here
  # gem 'susy', require: 'susy'
  # gem 'redcarpet', require: 'redcarpet'
end