development:
  host: dominategaming.johnepperson.com:8080
  email: admin@johnepperson.com
  password: testpass
  # api_key: <your api key here>
staging:
  host: dominategaming.johnepperson.com:8080
  email: admin@johnepperson.com
  password: testpass
  # api_key: <your api key here>
production:
  # host: dominategaming.johnepperson.com:8080
  # email: admin@johnepperson.com
  # password: testpass
  # api_key: <your api key here>